name: ytp_new
description: "An application for managing your Youtube Playlists."
publish_to: "none"
version: 1.1.1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  dynamic_color: ^1.7.0
  file_picker: ^6.2.0
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  provider: ^6.1.2
  receive_sharing_intent: ^1.6.7
  shared_preferences: ^2.2.2
  timeago: ^3.6.1
  url_launcher: ^6.2.5
  youtube_explode_dart: ^2.1.0
  background_fetch: ^1.3.2
  flutter_local_notifications: ^17.0.0
  window_manager: ^0.3.8
  package_info_plus: ^7.0.0
  permission_handler: ^11.3.1
  # flutter_launcher_icons: ^0.13.1

# flutter_launcher_icons:
#   image_path_android: "assets/app_icon.png"
#   android: true
#   windows:
#     generate: true
#     image_path: "assets/app_icon.png"

#? uncomment the above and run:
#? flutter pub run flutter_launcher_icons
#? to generate new icons

dev_dependencies:
  test: ^1.24.9
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
